### PR TITLE
Adding code to cache the config at laravel

### PR DESCRIPTION
**Pull request by samuel-lujan**
| Is bugfix?    | ✔️
| Tests pass?   | ✔️
#251

### CODE REVIEW

**Comment by peterangelov** [comment]
IMHO caching the config is not a mandatory step to make this package work. It is merely a good suggestion for performance optimisation.

Also, you left the sentence "Lumen does not support this command...." on line 141 which looks like Lumen does not support configuration caching, but in fact, it relates to `vendor:publish` command.

**Comment by samuel-lujan** [comment]
Ups.. that's my bad, I'm fixing it!

**Comment by J-Brk** [comment]
I don't think this should be in the documentation. Config caching is completely unrelated to this package.

**Comment by samuel-lujan** [comment]
> I don't think this should be in the documentation. Config caching is completely unrelated to this package.

When I was setting up this package, I had some troubles with cache. then I thought this would help the beginners. but there's no problem if this don't be at the documentation.

**Comment by J-Brk** [comment]
> > I don't think this should be in the documentation. Config caching is completely unrelated to this package.
> 
> When I was setting up this package, I had some troubles with cache. then I thought this would help the beginners. but there's no problem if this don't be at the documentation.

You had some troubles with the configuration cache; probably because you cached the config earlier 😉
When you're still working on your project; you better don't cache the configuration at all.

**Comment by samuel-lujan** [comment]
> 
> 
> > > I don't think this should be in the documentation. Config caching is completely unrelated to this package.
> > 
> > 
> > When I was setting up this package, I had some troubles with cache. then I thought this would help the beginners. but there's no problem if this don't be at the documentation.
> 
> You had some troubles with the configuration cache; probably because you cached the config earlier 😉
> When you're still working on your project; you better don't cache the configuration at all.

Got it! thanks :) Than you think that I could close this Pull Request?

**Pull request closed without merging**
