### PR TITLE
Add possibility to generate few JsonLd Group

### PR DESCRIPTION
**Pull request by yepzy**
On a project I have page that require few JsonLd group and with the current implement, only one JsonLd can be filled.

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | -

### CODE REVIEW

**Comment by Okipa** [comment]
+1.

Would be great indeed to have the ability to generate multiple JsonLD meta, it is sometimes required : https://stackoverflow.com/questions/30723531/best-json-ld-practices-using-multiple-script-elements.

There may be a better way to implement that by modifying the JsonLD architecture ?

Would you have another idea on how implementing this ? We may update this PR if you point us the way you would accept such a feature.

**Comment by vinicius73** [comment]
@yepzy thanks a lot for this PR
Is a big feature.

@emtudo can you help me to review this PR?

**Comment by emtudo** [comment]
It's ok!

thanks!

**Comment by Okipa** [comment]
Thanks ! Congratz @yepzy ;)

**Pull request merged**
