### PR TITLE
Fix generated tags from array

### PR DESCRIPTION
**Pull request by BulgarianHealer**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | I dont know what do you mean by BC
| Tests pass?   | N/A
| Fixed issues  |  #74

### CODE REVIEW

**Comment by vinicius73** [comment]
Thanks
Can you provide a test?

**Comment by BulgarianHealer** [comment]
I will not be able to provide test, but this is example of how is working.
````php
$tags = ['Example', 'tags', 'test'];

OpenGraph::setArticle([
        "tag" => $tags,
]);

//Output
<meta property="article:tag" content="Example" />
<meta property="article:tag" content="tags" />
<meta property="article:tag" content="test" />

```
I'm adding and other things and for so long I didn't have any problems.

**Comment by zafranf** [comment]
up,

**Comment by vinicius73** [comment]
Closed by #233

**Pull request closed without merging**
