### PR TITLE
Double quote escaping

### PR DESCRIPTION
**Pull request by J-Brk**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #189 

- Implementation of escaping of double quotes as mentioned in #189.
- Equalized code structure between OpenGraph and TwitterCards for neater implementation of the fix.

### CODE REVIEW

**Comment by J-Brk** [comment]
@vinicius73 Can you see why my PR is only running 1 check instead of 2 & can you merge it?

**Comment by J-Brk** [comment]
@vinicius73 Can you give this one a push for merging?

Sometimes it takes very long before some issues are resolved and I guess you are very busy. Maybe you can assign me and some others some roles so we can boost up the development / progress of this package?

**Comment by J-Brk** [comment]
A little reminder about this merge @vinicius73 :)

**Comment by vinicius73** [comment]
Hi @J-Brk sorry for the long delay.
I will merge this and promote you to a contributor, what do you think?

**Pull request merged**
