### PR TITLE
Laravel 11 Support

### PR DESCRIPTION
**Pull request by poldixd**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | 

This pull request adds Laravel 11 support.

### CODE REVIEW

**Comment by Rattone** [comment]
The last PR was merged almost a year ago... is this package still maintained?

**Review by J-Brk — APPROVED** [review]

**Comment by J-Brk** [comment]
> The last PR was merged almost a year ago... 
> @J-Brk is this package still maintained?

The package is still maintained and very stable. Thank you for contributing!

**Comment by J-Brk** [comment]
Seems the tests have failed, can you add the exclude for the older PHP versions?

**Comment by poldixd** [comment]
I dropped PHP and Laravel versions which are end of life.

https://endoflife.date/php
https://endoflife.date/laravel

I'm not sure if I can drop `phpspec/phpspec:~5.1.1` as well.

**Comment by rickgoemans** [comment]
Any news on this PR? Looking forward to upgrading my application(s) to Laravel 11 but this one is holding me back.

**Comment by J-Brk** [comment]
Sorry for the lack response & thanks for tagging me! The changes look good to me but seems we are still failing some tests... Do you have time to quickly fix the the phpunit config? If not I will try to adjust it myself in a few hours

**Comment by poldixd** [comment]
Unfortunately, I won't be able to make it today. Tomorrow I could have a look at the problem.

**Comment by poldixd** [comment]
@J-Brk my local tests are now passes. Maybe you can approve my changes.

```
PHPUnit 10.5.13 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.3
Configuration: /Users/nils/Packages/poldixd/seotools/phpunit.xml.dist

................................................................. 65 / 83 ( 78%)
..................                                                83 / 83 (100%)

Time: 00:00.182, Memory: 26.00 MB

OK (83 tests, 103 assertions)
```

**Comment by rickgoemans** [comment]
@J-Brk Is there anything you could tell to when this will be merged/released?

**Comment by poldixd** [comment]
You can use temporary my repo for this package:

composer.json

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/poldixd/seotools.git"
        }
    ]
}
```

and then `composer require artesaos/seotools`

**Review by emtudo — APPROVED** [review]

**Comment by J-Brk** [comment]
Thanks for jumping in @emtudo. I still wanted to do some more checks to make sure it works well but due to time restrains haven't been able to unfortunately. 

To prevent others from having to wait to use this, can you quickly release it as new version?

**Comment by emtudo** [comment]
ok @J-Brk I was going to wait for you since you started, but since you asked.

**Comment by emtudo** [comment]
New version released!

**Pull request merged**
